// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smlvscbgsyyisjulinbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtbHZzY2Jnc3l5aXNqdWxpbmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjQ4NzcsImV4cCI6MjA2OTk0MDg3N30.c2OFXa76X9qkjyIyKh1Yf86YDJ1mYwG78Gw9LXRz80g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});